name: Publish image to Docker hub v2 ghcr
on:
    push:
        branches:
        - main
    workflow_dispatch:
        inputs:
            tag:
                description: 'Docker image tag'
                required: true
                default: '1.0.0'

jobs:
    publish_image:
        runs-on: ubuntu-latest
        env:
            TAG: ${{ github.event.inputs.tag || '1.0.0' }}
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PORT: 22
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Login to Docker registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker image
          run: |
            docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/python-app:${{ env.TAG }} .
        - name: Save docker image
          run: |
            mkdir -p ~/image-cache
        - name: Push Docker image
          run: |
            docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/python-app:${{ env.TAG }}


